# Generated by Django 5.2.3 on 2026-06-15 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalactivite',
            options={'ordering': ['-date_action']},
        ),
        migrations.AddField(
            model_name='journalactivite',
            name='element',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalactivite',
            name='module',
            field=models.CharField(default='SYSTEME', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='adresse_ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
