# Generated by Django 5.2.3 on 2026-06-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journalactivite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='adresse_ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='element',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='module',
            field=models.CharField(default='SYSTEME', max_length=50),
        ),
    ]
