# Generated by Django 5.2.3 on 2026-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('type_message', models.CharField(choices=[('SAT', 'Satisfaction'), ('REC', 'Réclamation'), ('SUG', 'Suggestion'), ('INC', 'Incident')], max_length=3)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('note', models.PositiveSmallIntegerField(default=5)),
                ('lu', models.BooleanField(default=False)),
                ('traite', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
