# Generated by Django 5.2.3 on 2026-05-30 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avitaillement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('nom_navire', models.CharField(max_length=150)),
                ('type_transport', models.CharField(choices=[('PIPELINE', 'Pipeline'), ('BARGE', 'Barge'), ('CAMION', 'Camion'), ('CAMIONS', 'Camions')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('destination', models.CharField(max_length=255)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('consignataire', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='StockCuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite_totale', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock_actuel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=1000, max_digits=15)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
