# Generated by Django 5.2.3 on 2026-06-02 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitaillement', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcuve',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockcuve',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='produits.produit'),
        ),
        migrations.AlterField(
            model_name='stockcuve',
            name='stock_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
