# Generated by Django 5.2.3 on 2026-05-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('ncc', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
